---
abstract: 'Secure management of iTans for online banking from'
author:
  - 'Maroš Kollár'
build_requires:
  Expect: 0
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-iTan
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBD::SQLite: 0
  DBI: 0
  DateTime: 0
  Moose: 0
  MooseX::App::Cmd: 0
  MooseX::Getopt: 0
  Params::Coerce: 0
  Path::Class: 0
  Text::Table: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/maros/App-iTan.git
version: 1.000
