---
abstract: 'Secure management of iTANs for online banking'
author:
  - 'Maroš Kollár'
build_requires:
  Expect: 0
  ExtUtils::MakeMaker: 6.59
  File::Temp: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-iTan
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Mac::Pasteboard: 0
requires:
  Crypt::Twofish: 0
  DBD::SQLite: 0
  DBI: 0
  DateTime: 0
  File::HomeDir: 0
  Moose: 0
  MooseX::App: 1.04
  MooseX::Types::Path::Class: 0
  Params::Coerce: 0
  Path::Class: 0
  Term::ReadKey: 0
  Text::Table: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/maros/App-iTan.git
version: 1.05
